"""Integration test: public and tenant schemas must have identical DDL.

Dumps columns, constraints, and indexes from information_schema / pg_indexes,
strips schema-name prefixes so any difference there is a real defect, and
asserts equality. Skipped when DATABASE_URL is not configured.
"""

from __future__ import annotations

import os
import re
import uuid
from collections.abc import Iterator

import pytest

pytestmark = pytest.mark.skipif(
    not os.environ.get("DATABASE_URL"),
    reason="DATABASE_URL not set; skipping live-Postgres schema diff",
)


@pytest.fixture(scope="module")
def database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    assert url is not None
    return url


@pytest.fixture(scope="module")
def tenant_schema(database_url: str) -> Iterator[str]:
    import psycopg

    from scripts.create_tenant import main as create_tenant_main
    from scripts.migrate import main as migrate_main

    assert migrate_main(["--schema", "public", "--database-url", database_url]) == 0

    name = f"osm_test_{uuid.uuid4().hex[:8]}"
    assert create_tenant_main([name, "--database-url", database_url]) == 0
    try:
        yield name
    finally:
        with psycopg.connect(database_url) as conn, conn.cursor() as cur:
            cur.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')
            conn.commit()


def _dump_columns(conn: object, schema: str) -> list[tuple[object, ...]]:
    import psycopg

    assert isinstance(conn, psycopg.Connection)
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT table_name, column_name, data_type, is_nullable,
                   column_default, udt_name
            FROM information_schema.columns
            WHERE table_schema = %s AND table_name <> 'schema_migrations'
            ORDER BY table_name, ordinal_position
            """,
            (schema,),
        )
        return list(cur.fetchall())


def _dump_constraints(conn: object, schema: str) -> list[tuple[object, ...]]:
    import psycopg

    assert isinstance(conn, psycopg.Connection)
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT table_name, constraint_type, constraint_name
            FROM information_schema.table_constraints
            WHERE table_schema = %s AND table_name <> 'schema_migrations'
            ORDER BY table_name, constraint_type, constraint_name
            """,
            (schema,),
        )
        return list(cur.fetchall())


def _dump_indexes(conn: object, schema: str) -> list[tuple[str, str]]:
    import psycopg

    assert isinstance(conn, psycopg.Connection)
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT tablename, indexdef
            FROM pg_indexes
            WHERE schemaname = %s AND tablename <> 'schema_migrations'
            ORDER BY tablename, indexname
            """,
            (schema,),
        )
        return list(cur.fetchall())


def _strip_schema(rows: list[tuple[object, ...]], schema: str) -> list[tuple[object, ...]]:
    pattern = re.compile(rf'\b{re.escape(schema)}\b|"{re.escape(schema)}"')
    # Postgres 16 omits the schema prefix from nextval() defaults on `public`
    # while Postgres 18 serialises them as `nextval('public.seq'::regclass)`.
    # After the schema-name strip we also drop the leftover `.` so `public`
    # and tenant schemas compare byte-equal across versions.
    orphan_dot = re.compile(r"_SCHEMA_\.")
    out: list[tuple[object, ...]] = []
    for row in rows:
        normalized = tuple(
            re.sub(
                r"\s+",
                " ",
                orphan_dot.sub("", pattern.sub("_SCHEMA_", v)),
            ).strip()
            if isinstance(v, str)
            else v
            for v in row
        )
        out.append(normalized)
    return out


def _normalize_constraints(
    rows: list[tuple[object, ...]], schema: str
) -> list[tuple[object, ...]]:
    # WHY: UNIQUE/CHECK/FK constraint names are autogenerated per-schema with
    # the table name, not the schema name, so they are stable; PK names
    # are `<table>_pkey`. Postgres 16.4+ also exposes auto-generated NOT NULL
    # CHECK constraints named `<schema_oid>_<table_oid>_<colnum>_not_null`;
    # drop those — the column-level NOT NULL is already captured via
    # `is_nullable` in `_dump_columns`.
    oid_not_null = re.compile(r"^\d+_\d+_\d+_not_null$")
    filtered = [row for row in rows if not oid_not_null.match(str(row[2]))]
    return _strip_schema(filtered, schema)


def test_schema_diff(database_url: str, tenant_schema: str) -> None:
    import psycopg

    with psycopg.connect(database_url) as conn:
        public_cols = _strip_schema(_dump_columns(conn, "public"), "public")
        tenant_cols = _strip_schema(_dump_columns(conn, tenant_schema), tenant_schema)

        public_cons = _normalize_constraints(_dump_constraints(conn, "public"), "public")
        tenant_cons = _normalize_constraints(
            _dump_constraints(conn, tenant_schema), tenant_schema
        )

        public_idx = _strip_schema(_dump_indexes(conn, "public"), "public")
        tenant_idx = _strip_schema(_dump_indexes(conn, tenant_schema), tenant_schema)

    assert public_cols == tenant_cols, "column layout diverged between public and tenant"
    assert public_cons == tenant_cons, "constraint layout diverged between public and tenant"
    assert public_idx == tenant_idx, "index layout diverged between public and tenant"
