-- migrations/0002_master_data_seed.sql
-- Schema preparation for master data seeding.
--
-- NOTE: actual INSERTs for the 26 master data profiles + 48 repos are
-- performed by Python (`src/db/seed_master_data.py::seed_all`) invoked from
-- `src/db/migrate.py::main` AFTER yoyo applies this migration. The seeding is
-- intentionally NOT inside this SQL file because:
--   1. `repos.local_path` is derived from `Path.home()` at runtime via
--      `src/git_utils.py::default_clone_dir` — not expressible in pure SQL.
--   2. Keeping `INSERT INTO profiles` out of yoyo lets legacy test fixtures
--      (e.g. `tests/test_db_repo_registry.py`) still see an empty profiles
--      table after `run_migrations()`. Production `migrate.py::main` seeds
--      both profiles and repos through the Python helper.
--
-- This migration exists primarily as the upgrade-safety hook below: pre-Wave-2
-- schemas may have a `profiles` table without the `description` column (the
-- `tests/test_db_migrate_upgrade.py` legacy-schema fixture simulates that
-- state). `seed_profiles` writes `description`, so the column must exist
-- before that runs.

-- Idempotent ALTER for upgrade path: legacy schemas may not yet have the
-- `description` column. No-op on modern schemas where 0001_initial.sql
-- already created it.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS description TEXT;
