-- migrations/m13_002_tenants_and_fks.sql
-- M13 "Multi-Tenant Wow" — P1 Control Plane (DDL only, ADR-0034 D1 + D7).
--
-- Changes in this migration (all additive, backward-compatible):
--
--   1. CREATE TABLE tenants  — authorization boundary for pooled multi-tenancy.
--      Rows with tenant_id IS NULL on child tables = shared/global scope.
--
--   2. ALTER TABLE api_keys      ADD COLUMN tenant_id  (nullable FK → tenants)
--      ALTER TABLE profiles      ADD COLUMN tenant_id  (nullable FK → tenants)
--      ALTER TABLE ssh_key_pairs ADD COLUMN tenant_id  (nullable FK → tenants)
--      ALTER TABLE repos         ADD COLUMN tenant_id  (nullable FK → tenants)
--      All NULL by default — existing rows are preserved as shared/global.
--
--   3. ALTER TABLE ssh_key_pairs ADD COLUMN key_type TEXT
--      CHECK (key_type IN ('deploy_key','access_key')) DEFAULT 'access_key'.
--      Supports per-tenant deploy-key credential model (ADR-0034 D7).
--
--   4. repos UNIQUE constraint change:
--      DROP UNIQUE(url, branch)    — old constraint prevents same upstream repo
--                                    from being registered under multiple tenant
--                                    profiles, which ADR-0034 D2 explicitly allows.
--      ADD  UNIQUE(url, branch, profile_id) — prevents true duplicates (same repo
--                                    under the same profile) while permitting
--                                    cross-profile/cross-tenant clones of the same
--                                    upstream URL.
--
--      NOTE: src/db/repo_registry.py::update_repo() pre-checks UNIQUE(url, branch)
--      globally (lines 704-714 as of M13 DDL phase).  That application-level check
--      becomes overly restrictive once tenants are active — it will reject a repo
--      registered under tenant A from being added under tenant B.  Updating that
--      check to scope to profile_id is owned by a separate application-code WI
--      (not this DDL-only migration).
--
-- Idempotency: every statement uses IF NOT EXISTS / DO $$ … END $$ guards so this
-- migration is safe to re-run on a production-shape database.

-- ---------------------------------------------------------------------------
-- 1. tenants table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tenants (
    id          SERIAL      PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    active      BOOLEAN     NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- 2. tenant_id FK columns on child tables (nullable; NULL = shared/global)
-- ---------------------------------------------------------------------------

-- api_keys
ALTER TABLE api_keys
    ADD COLUMN IF NOT EXISTS tenant_id INTEGER
    REFERENCES tenants(id) ON DELETE CASCADE;

-- profiles  (NULL = shared base profile, e.g. odoo_17)
ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS tenant_id INTEGER
    REFERENCES tenants(id) ON DELETE CASCADE;

-- ssh_key_pairs
ALTER TABLE ssh_key_pairs
    ADD COLUMN IF NOT EXISTS tenant_id INTEGER
    REFERENCES tenants(id) ON DELETE CASCADE;

-- repos
ALTER TABLE repos
    ADD COLUMN IF NOT EXISTS tenant_id INTEGER
    REFERENCES tenants(id) ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 3. ssh_key_pairs.key_type  (ADR-0034 D7 — per-tenant deploy-key model)
-- ---------------------------------------------------------------------------

ALTER TABLE ssh_key_pairs
    ADD COLUMN IF NOT EXISTS key_type TEXT
    NOT NULL DEFAULT 'access_key'
    CHECK (key_type IN ('deploy_key', 'access_key'));

-- ---------------------------------------------------------------------------
-- 4. repos UNIQUE constraint: replace (url, branch) with (url, branch, profile_id)
-- ---------------------------------------------------------------------------

-- Drop the old global unique constraint if it still exists.
-- Constraint was named by Postgres using the default autogenerated name
-- "repos_url_branch_key" (from UNIQUE(url, branch) in 0001_initial.sql).
-- We guard the DROP with an existence check for full idempotency.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
         WHERE constraint_name = 'repos_url_branch_key'
           AND table_name      = 'repos'
    ) THEN
        ALTER TABLE repos DROP CONSTRAINT repos_url_branch_key;
    END IF;
END $$;

-- Add the narrower per-profile unique constraint.
-- IF NOT EXISTS syntax for ADD CONSTRAINT is not supported in all PG16 paths
-- via ALTER TABLE directly, so we guard with a DO block.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
         WHERE constraint_name = 'repos_url_branch_profile_key'
           AND table_name      = 'repos'
    ) THEN
        ALTER TABLE repos ADD CONSTRAINT repos_url_branch_profile_key
            UNIQUE (url, branch, profile_id);
    END IF;
END $$;

-- Supporting indexes for FK lookups (tenant_id columns).
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant_id    ON api_keys    (tenant_id);
CREATE INDEX IF NOT EXISTS idx_profiles_tenant_id    ON profiles    (tenant_id);
CREATE INDEX IF NOT EXISTS idx_ssh_key_pairs_tenant  ON ssh_key_pairs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_repos_tenant_id       ON repos       (tenant_id);
