-- migrations/m9_005_active_sessions.sql
-- M9 Auth Wow: create active_sessions table for server-side session store.
--
-- Findings addressed:
--   F7 — No server-side session store: stolen cookie is valid for 8 h with no
--        way to revoke it instantly.  With this table, logout/revoke simply
--        deletes the row; auth middleware rejects any session_id not found here.
--
-- Design notes:
--   * `session_id` is an opaque token (UUID or secrets.token_urlsafe(32))
--     generated by the application; stored as TEXT to avoid UUID type dependency.
--   * `user_id` FK references webui_users(id) added in m9_001_oauth_columns.sql.
--     ON DELETE CASCADE: deleting a user revokes all their sessions.
--   * `last_seen` is updated on each authenticated request (sliding window).
--   * `mfa_verified_at` records when the user most recently completed an MFA
--     challenge.  NULL = MFA not yet verified in this session.  Used by
--     W-RS (restore upload) and other operations requiring fresh MFA.
--   * Expired sessions are cleaned up by the application or a periodic job
--     (DELETE WHERE expires_at < NOW()).

CREATE TABLE IF NOT EXISTS active_sessions (
    session_id      TEXT        PRIMARY KEY,
    user_id         INTEGER     NOT NULL REFERENCES webui_users(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_address      INET,
    user_agent      TEXT,
    mfa_verified_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON active_sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_sessions_expires
    ON active_sessions (expires_at);
